/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { OutlineItemListRelationFilter } from "../../outlineItem/base/OutlineItemListRelationFilter";
import { SceneListRelationFilter } from "../../scene/base/SceneListRelationFilter";

@InputType()
class ChapterWhereInput {
  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  chapterNumber?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  content?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  novelId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => OutlineItemListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OutlineItemListRelationFilter)
  @IsOptional()
  @Field(() => OutlineItemListRelationFilter, {
    nullable: true,
  })
  outlineItems?: OutlineItemListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => SceneListRelationFilter,
  })
  @ValidateNested()
  @Type(() => SceneListRelationFilter)
  @IsOptional()
  @Field(() => SceneListRelationFilter, {
    nullable: true,
  })
  scenes?: SceneListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;
}

export { ChapterWhereInput as ChapterWhereInput };
