/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Scene } from "./Scene";
import { SceneCountArgs } from "./SceneCountArgs";
import { SceneFindManyArgs } from "./SceneFindManyArgs";
import { SceneFindUniqueArgs } from "./SceneFindUniqueArgs";
import { CreateSceneArgs } from "./CreateSceneArgs";
import { UpdateSceneArgs } from "./UpdateSceneArgs";
import { DeleteSceneArgs } from "./DeleteSceneArgs";
import { OutlineItemFindManyArgs } from "../../outlineItem/base/OutlineItemFindManyArgs";
import { OutlineItem } from "../../outlineItem/base/OutlineItem";
import { Chapter } from "../../chapter/base/Chapter";
import { SceneService } from "../scene.service";
@graphql.Resolver(() => Scene)
export class SceneResolverBase {
  constructor(protected readonly service: SceneService) {}

  async _scenesMeta(
    @graphql.Args() args: SceneCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Scene])
  async scenes(@graphql.Args() args: SceneFindManyArgs): Promise<Scene[]> {
    return this.service.scenes(args);
  }

  @graphql.Query(() => Scene, { nullable: true })
  async scene(
    @graphql.Args() args: SceneFindUniqueArgs
  ): Promise<Scene | null> {
    const result = await this.service.scene(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Scene)
  async createScene(@graphql.Args() args: CreateSceneArgs): Promise<Scene> {
    return await this.service.createScene({
      ...args,
      data: {
        ...args.data,

        chapter: args.data.chapter
          ? {
              connect: args.data.chapter,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Scene)
  async updateScene(
    @graphql.Args() args: UpdateSceneArgs
  ): Promise<Scene | null> {
    try {
      return await this.service.updateScene({
        ...args,
        data: {
          ...args.data,

          chapter: args.data.chapter
            ? {
                connect: args.data.chapter,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Scene)
  async deleteScene(
    @graphql.Args() args: DeleteSceneArgs
  ): Promise<Scene | null> {
    try {
      return await this.service.deleteScene(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [OutlineItem], { name: "outlineItems" })
  async findOutlineItems(
    @graphql.Parent() parent: Scene,
    @graphql.Args() args: OutlineItemFindManyArgs
  ): Promise<OutlineItem[]> {
    const results = await this.service.findOutlineItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Chapter, {
    nullable: true,
    name: "chapter",
  })
  async getChapter(@graphql.Parent() parent: Scene): Promise<Chapter | null> {
    const result = await this.service.getChapter(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
