/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { JsonFilter } from "../../util/JsonFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { ChapterWhereUniqueInput } from "../../chapter/base/ChapterWhereUniqueInput";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { OutlineItemListRelationFilter } from "../../outlineItem/base/OutlineItemListRelationFilter";

@InputType()
class SceneWhereInput {
  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  beats?: JsonFilter;

  @ApiProperty({
    required: false,
    type: () => ChapterWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ChapterWhereUniqueInput)
  @IsOptional()
  @Field(() => ChapterWhereUniqueInput, {
    nullable: true,
  })
  chapter?: ChapterWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  content?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => OutlineItemListRelationFilter,
  })
  @ValidateNested()
  @Type(() => OutlineItemListRelationFilter)
  @IsOptional()
  @Field(() => OutlineItemListRelationFilter, {
    nullable: true,
  })
  outlineItems?: OutlineItemListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;
}

export { SceneWhereInput as SceneWhereInput };
